#!/bin/bash

set -euo pipefail

readonly TEST_DIR=$(mktemp --tmpdir --directory lit-test.XXXXXX)

echo "== Using $TEST_DIR"
pushd "$TEST_DIR"

echo "== Initializing repository"
lit init

echo "== Creating the first commit"
cat >file1 <<-EOF
	This is the first line of the first file. 🚀
	This is the second line of the first file.
EOF

# Let's check the status. Should look something like this:
# Changes:
#   Add file1
lit status

# We expect the first commit to be identified as r0.
lit commit "Add file1"


echo "== Creating more commits"
echo >>file1 "A third line is added to the first file."

# Let's check the status again, just to be sure.
lit status

# This one would be r1.
lit commit "Extend file1"

echo >>file1 "A forth line is added."

# This should be r2.
lit commit "Extend file1 even further"

echo "== Creating testBranch here"
lit checkout -b testBranch

echo "== Switching back to master"
lit checkout master

echo "== Displaying graph"

# o ← r2 Extend file1 even further
# o   r1 Extend file1
# o   r0 Add file1
lit log

echo "== Inspecting r0"
lit show r0

echo "== Switching to r0"
lit checkout r0

# Checking the file content.
diff -s file1 - <<-EOF
	This is the first line of the first file. 🚀
	This is the second line of the first file.
EOF

echo "== Switching back to r2"
lit checkout r2

# Checking the file content again.
diff -s file1 - <<-EOF
	This is the first line of the first file. 🚀
	This is the second line of the first file.
	A third line is added to the first file.
	A forth line is added.
EOF

echo "== Adding and discarding changes"
echo >>file1 "This fifth line should be gone in an instant."
lit checkout

# Let's confirm.
diff -s file1 - <<-EOF
	This is the first line of the first file. 🚀
	This is the second line of the first file.
	A third line is added to the first file.
	A forth line is added.
EOF

echo "== Creating another branch"
lit checkout testBranch
mkdir subfolder
cat >subfolder/file2 <<-EOF
	This is the first line of the second file.
	And another line in the second file.
EOF

# This should be r3.
lit commit "Add file2"

#   o ← r3 Add file2
# o │   r2 Extend file1 even further
# o │   r1 Extend file1
# o─┘   r0 Add file1
lit log

echo "== Going back"
lit checkout master

echo "== another file"
echo >>file3 "this is file 3"
lit commit "Add file3"

# file2 should be gone.
test ! -f subfolder/file2

echo "== Merging (no conflict)"

# This creates a merge commit r5.
lit merge testBranch


# file2 should now be present.
diff -s subfolder/file2 - <<-EOF
	This is the first line of the second file.
	And another line in the second file.
EOF

# o←┐  ← r5 Merge r4 into r3
# o  │    r4 Add file3
# │  o    r3 Add file2
# o──┘    r2 Extend file1 even further
# o       r1 Extend file1
# o       r0 Add file1
lit log


echo "== Setting up a conflict"
echo >>file1 "Fifth line on top of r5."
lit commit "Extend file1 one way" # r6


echo "== Switching back to testBranch"
lit checkout testBranch


echo >>file1 "Fifth line on top of r4."
lit commit "Extend file1 another way" # r7


#    o ←  r7 Extend file1 another way
# o  │    r6 Extend file1 one way
# o←┐  ← r5 Merge r4 into r3
# o  │    r4 Add file3
# │  o    r3 Add file2
# o──┘    r2 Extend file1 even further
# o       r1 Extend file1
# o       r0 Add file1
lit log

# Going back and merging.
lit checkout master
lit merge testBranch || true

# Let's check all file versions:
#   Current commit
diff -s file1 - <<-EOF
	This is the first line of the first file. 🚀
	This is the second line of the first file.
	A third line is added to the first file.
	A forth line is added.
	Fifth line on top of r5.
EOF

#   other branch
diff -s file1.r7 - <<-EOF
	This is the first line of the first file. 🚀
	This is the second line of the first file.
	A third line is added to the first file.
	A forth line is added.
	Fifth line on top of r4.
EOF


#  common base
diff -s file1.r2 - <<-EOF
	This is the first line of the first file. 🚀
	This is the second line of the first file.
	A third line is added to the first file.
	A forth line is added.
EOF

# Let's simulate some conflict resolution.
echo >>file1 "Sixth line added during merge conflict."

# Before continuing we need to cleanup the leftover files.
rm file1.r7 file1.r2

lit commit "Merge r7 into r6" # r8

# Let's verify the final result.

diff -s file1 - <<-EOF
	This is the first line of the first file. 🚀
	This is the second line of the first file.
	A third line is added to the first file.
	A forth line is added.
	Fifth line on top of r5.
	Sixth line added during merge conflict.
EOF

# o←┐  ← r8 Merge r7 into r6
# │  o ←  r7 Extend file1 another way
# o  │    r6 Extend file1 one way
# o←┐  ← r5 Merge r4 into r3
# o  │    r4 Add file3
# │  o    r3 Add file2
# o──┘    r2 Extend file1 even further
# o       r1 Extend file1
# o       r0 Add file1
lit log

echo "== Cleanup"
popd
rm -r "$TEST_DIR"
